apiVersion: apps/v1
kind: Deployment
metadata:
  name: kumojin-backend
  namespace: default
  labels:
    app: kumojin-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kumojin-backend
  template:
    metadata:
      labels:
        app: kumojin-backend
    spec:
      containers:
        - name: kumojin-backend
          image: kumojin-backend
          env:
            - name: SERVICE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['app']
            - name: NODE_ENV
              value: development
